spring.application.name=gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

## Gateway Routes
spring.cloud.gateway.routes[0].id=fitness
spring.cloud.gateway.routes[0].uri=lb://FITNESS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=activityEvent-Service
spring.cloud.gateway.routes[1].uri=lb://ACTIVITYEVENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activities/**

spring.cloud.gateway.routes[2].id=aiService
spring.cloud.gateway.routes[2].uri=lb://AISERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recommendations/**

